server {
    listen 8080;
    server_name  localhost;
    absolute_redirect off;

    ${STAC_PREFIX_REDIRECT}
    location ${STAC_PATH_PREFIX} {
        alias  /usr/share/nginx/html/;
        index  index.html;
        try_files $uri $uri/ ${STAC_PATH_PREFIX}index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
