name: Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  locales:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v4
      - run: npm ci
      - name: I18N messages for stac-fields are complete
        run: npm run i18n:fields
      - uses: infotroph/tree-is-clean@v1
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v4
      - run: npm install
      - name: Linting
        run: npm run lint
