name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v6
      - run: npm ci
      - run: npm run build
        env:
          SB_footerLinks: '[{"label":"Made with ♥️ by moreGeo","url":"https://moregeo.it"},{"label":"Imprint","url":"https://moregeo.it/imprint"},{"label":"Privacy Policy","url":"https://moregeo.it/privacy"}]'
      - uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: w021d7df.kasserver.com
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true
          local-dir: ./dist/
          exclude: |
            **/report.html
