name: Dist

on:
  release:
    types:
      - published

jobs:
  build-and-attach-release:
    runs-on: ubuntu-latest
    name: Build app and upload to release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Archive build output
        run: |
          cd dist
          zip -r ../dist.zip .

      - name: Upload build to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}