name: Deploy fao-catalog to Cloud Run
run-name: Deploy fao-catalog to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Deployment environment'
        options:
          - review
      branch:
        type: string
        description: 'Branch to deploy'
        required: false

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: fao-catalog-${{ github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          token_format: 'access_token'
          access_token_lifetime: '120s'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Authenticate Docker to Google Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        env:
          SB_FOOTER_LINKS: '[{"label":"Made with ♥️ by moreGeo","url":"https://moregeo.it"},{"label":"Imprint","url":"https://moregeo.it/imprint"},{"label":"Privacy Policy","url":"https://moregeo.it/privacy"}]'
        run: |
          docker build \
            --build-arg ENVIRONMENT=${{ github.event.inputs.environment }} \
            --build-arg SB_footerLinks="$SB_FOOTER_LINKS" \
            -f Dockerfile \
            -t ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/fao-catalog/fao-catalog:${{ github.sha }} \
            .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/fao-catalog/fao-catalog:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fao-catalog \
            --service-account "${{ vars.APPLICATION_SERVICE_ACCOUNT }}" \
            --image ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/fao-catalog/fao-catalog:${{ github.sha }} \
            --platform managed \
            --region ${{ vars.GCP_REGION }} \
            --allow-unauthenticated
